### PR TITLE
SystemPropertiesRestoreRule: convenience constructor

### PR DESCRIPTION
**Pull request by dsmiley**
See #293 
I didn't add a test; it's not evident the "ignoredProperties" is tested either.  I tried to find a place to _use_ the convenience constructors, which led me to something pretty close: Test010Zombies which sets two system properties at the start of the test, neither of which are dynamic.  If it was one sys prop, I'd use the name-value constructor.  For more than one, I'd like to use Java 9's "Map.of(....)" or a Guava equivalent but neither are present for this project.  Opinions?

### CODE REVIEW

**Comment by dsmiley** [comment]
"SystemPropertiesRestoreRule" is a bit of a mouthful, and I also observe "SystemPropertiesInvariantRule".  Wouldn't all tests ideally use SystemPropertiesRestoreRule?  Maybe a single general purpose "SystemPropertiesRule" that had a build-like usage:
````
@Rule public final SystemPropertiesRule SYS_PROP_RULE = new SystemPropertiesRule()
  .setProperty("foo", "123")
  .setProperty("bar","456")
  .restoreAllProperties(true) // the default (matching SystemPropertiesRestoreRule) but be explicit to show it can be disabled
  .failIfChanged(false); // equivalent to SystemPropertiesInvariantRule; default false
````
Or maybe some separate builder pattern class that just returns a TestRule from build(), thus we end up with immutable TestRule instances instead of directly modifying?

**Comment by dweiss** [comment]
Hi David. Sorry about the delay - covid, work and a broken tooth. I like the build-style pattern. I think by default the failIfChanged should be set to true so that an empty constructor would just create a no-changes style invariant rule.

The only problem I see is with restore-all as property scans require additional permissions if security manager is enabled. So if restore-all is off, the code should just read/write the explicitly set properties.

**Comment by dsmiley** [comment]
Life gets in the way; not need to apologize.  I'm glad to hear you like the builder-style approach.  I'll work on a more all-encompassing PR with the features showed above.  Probably this weekend.

> failIfChanged should be set to true

Curious -- why is this a good default?  I love resetting as a default but I think failing as a default is not an error on the part of the code being tested.  Code sets System properties to switch feature flags and/or make adjustments in a test env.  With this proposal of yours, assuming I accept this default in tests, the test would have to undo everything it sets, (including all props that might be set outside the literal test file itself.  Do you disagree?

**Comment by dweiss** [comment]
My viewpoint is that code (by default) shouldn't touch (modify) system properties... if it does, it should clean up after it's done so. Perhaps I misunderstood you but I though failIfChanged would apply to any system properties not explicitly listed in setProperty - these setProperty ones would be restored by the rule and they wouldn't cause a failure, even if modified by the test (rule's scope)?

**Comment by dsmiley** [comment]
> My viewpoint is that code (by default) shouldn't touch (modify) system properties... if it does, it should clean up after it's done so. 

Okay... I can appreciate that it's preferable for some projects (e.g. that which produces a library) but not others.  And that furthermore, it might make more sense on the non-test code (don't want non-test code manipulating Sys props) ... but less sure about the test code/infrastructure that might be using the flags.

> Perhaps I misunderstood you but I though failIfChanged would apply to any system properties not explicitly listed in setProperty - these setProperty ones would be restored by the rule and they wouldn't cause a failure, even if modified by the test (rule's scope)?

Correct.

**Comment by dweiss** [comment]
Well, better late than never. :)

**Pull request merged**
