### PR TITLE
 Fixes GH-281: Make RandomizedRunner extensible.

### PR DESCRIPTION
**Pull request by coderplay**
This PR make `RandomizedRunner` extensible, with which developer is able to add more rules to wrap the test Statement.

### CODE REVIEW

**Comment by dweiss** [comment]
Hmm... wouldn't it be better to create a parent test class and set up your rules there (common for all tests)? Public/ protected methods are always a liability in case of changes so I'd rather have it in minimalistic style.

**Comment by dweiss** [comment]
But what's the reason you want to hook into these low-level implementation details? BlockJUnit4ClassRunner has been changing over time as well... I don't think it's particularly useful to hook in there at this level -- you should use the public infrastructure JUnit offers instead - then it should work the same, whatever runner you choose.

**Comment by coderplay** [comment]
Hi Dawid, thank you for your feedbacks.   I am a Lucene developer. Lucene's test cases is highly depends on `RandomizedRunner`. see 

https://github.com/apache/lucene-solr/blob/master/lucene/test-framework/src/java/org/apache/lucene/util/LuceneTestCase.java

I tried with junit runners to run lucene tests,   but failed because of many special annotations or settings only honored by  `RandomizedRunner`. For example, now I want to mix the function of 
BMUnitRunner to implement fault injection in order to enhance lucene's fault tolerance.

https://github.com/bytemanproject/byteman/blob/master/contrib/bmunit/src/org/jboss/byteman/contrib/bmunit/BMUnitRunner.java

I didn't find any other way besides this. Please let me know if you can think of other ways since you are an expert on this area.

**Comment by dweiss** [comment]
Lucene test cases do inherit from LuceneTestCase for a reason -- many checks are already in there. This is irrelevant to what you're trying to do, however. I don't think you'll be able to mix different parent runners with each other -- this will just not work, even if you have public access to Statement objects. Runners own the world and many assumptions stem from that. Byteman looks like AspectJ to me; there should be a way to inject bytecode manipulation via an agent (externally).

If you really want to combine byteman's test runner with randomizedtesting I'm afraid you'll have to fork the project and try it out separately (like I said, I don't think it's a good idea though).

**Comment by dweiss** [comment]
I'm a Lucene developer myself, actually and I wonder what is this "fault injection" you have in mind and how having access to statements helps it... Why don't you fork the project, set up an example and demonstrate what you're trying to achieve first? I really wouldn't want people to subclass RandomizedRunner. It was specifically designed to mimic JUnit's default implementation in behavior but *not* in the implementation details it provides.

**Comment by coderplay** [comment]
Hi Dawid,  The idea is similar to hadoop's FI framework which is based on AspectJ. https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-hdfs/FaultInjectFramework.html
We can inject faults from any layer of the application. This is especially helpful for distributed system like Elasticsearch, where we can simulate some lower level issues while testing , like disk error, merge fail, ordinals map out of memory, etc.

Different from AspectJ which do static weaving, our idea is more towards runtime dynamic injection. Where we can simply add an annotation to the target class or method and change it behavior by injecting some errors.

Below is an example.
https://gist.github.com/coderplay/82632cc322d4a4eb7f78e539ba4db355

I am kind of agree with your opinion on the maintainability of future changes if make those methods protected. How about adding a listener to `RandomizedRunner` ? Through chain of listeners we can wrap the original Statement returned by `RandomizedRunner` from test class/method levels. It's something like network filters. Does this idea sound good to  you?

**Comment by dweiss** [comment]
Ok, I get the idea. What I'm still missing is why this can't be done at test base class level with a simple wrapping rule. This is exactly what rules were designed for and those methods in the inherited runner are equivalent to having a single parent wrapper rule in the class being tested.

The simplest way to do it in Lucene, for example, would be to create a superclass for LuceneTestCase, have it extend Assert (like it was previously) but declare all "around" rules for both class and test case levels. This could be called "InjectionRulesParentClass" or something.

https://github.com/apache/lucene-solr/blob/master/lucene/test-framework/src/java/org/apache/lucene/util/LuceneTestCase.java#L220

Because JUnit mandates the ordering of parent-then-child rule processing you'd effectively get what you're trying to do by extending the runner directly. The benefits are that it'd be clearer what is happening (no magic a the runner level, rules order and content modifiable within the project) and it'd even work with newer/ different test runners. It's also consistent with what we're doing in LuceneTestCase already, see the rule chain here, for example:

https://github.com/apache/lucene-solr/blob/master/lucene/test-framework/src/java/org/apache/lucene/util/LuceneTestCase.java#L220

This is the part I'm missing here -- why isn't the rule-based scenario a better fit? Why do you need to subclass the runner?

**Pull request closed without merging**
