### PR TITLE
Add a security-manager test/example and clean up permissions

### PR DESCRIPTION
**Pull request by rmuir**
This makes it possible to reduce the tons of permissions needed currently, and only grant them to the test jar.

### CODE REVIEW

**Comment by rmuir** [comment]
By the way, I migrated all of our ES code to this snap and removed a ton of permissions and tightened the security and haven't faced any problems. In parallel ryan has done the same thing with gradle.

So I know the "example"/test is not exactly mindblowing but things do work and its simple. See you when you get back from vacation!

**Comment by dweiss** [comment]
This looks awesome, Robert. Thanks! I spotted a few copy/paste things (Lucene in comments, etc.), but I'll clean them up later, it can go in as is.

**Comment by dweiss** [comment]
Hmm... Java 1.6 doesn't like some of the permissions (the link one I guess).

http://builds.carrot2.org/browse/RNDTEST-SOFTWARE-JDK16-67/log

```
[INFO] java.security.policy: error adding Permission, java.io.FilePermission:
21-Sep-2015 13:30:39	        java.lang.IllegalArgumentException: invalid permission: read,readlink,write,delete,execute
21-Sep-2015 13:30:39	WARN: Exception at main loop level. -> java.security.AccessControlException: access denied (java.io.FilePermission /mnt/work/bamboo-home/xml-data/build-dir/RNDTEST-SOFTWARE-JDK16/examples/security-manager/target/junit4-J0-20150921_133035_792.events read)
21-Sep-2015 13:30:39	        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:399)
21-Sep-2015 13:30:39	        at java.security.AccessController.checkPermission(AccessController.java:557)
21-Sep-2015 13:30:39	        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
21-Sep-2015 13:30:39	        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
21-Sep-2015 13:30:39	        at java.io.File.isFile(File.java:837)
21-Sep-2015 13:30:39	        at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.main(SlaveMain.java:316)
21-Sep-2015 13:30:39	        at com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe.main(SlaveMainSafe.java:10)
```

**Comment by dweiss** [comment]
I'll just remove readlink, it's an example after all.

**Comment by rmuir** [comment]
Oops, sorry about the readlink mistake!

**Pull request merged**
